name: routemaster
description: Easy-to-use Navigator 2.0 router for web, mobile and desktop. URL-based routing, simple navigation of tabs and nested routes.
version: 1.0.2
homepage: https://github.com/tomgilder/routemaster

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  path: ^1.8.3
  collection: ^1.17.2
  equatable: ^2.0.5


dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
